// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetStatus():Promise<main.StatusSnapshot>;

export function GetStorageInfo():Promise<main.StorageInfo>;

export function ListDatabases():Promise<Array<main.DBNode>>;

export function ListSchemas(arg1:string):Promise<Array<main.SchemaNode>>;

export function ListTables(arg1:string,arg2:string):Promise<Array<main.TableNode>>;

export function OpenDataFolder():Promise<void>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
